/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Korea Investment API
 * 
[OpenAPI json 링크](http://localhost:8080/swagger.json)

[API 문서 링크](https://api.koreainvestment.com/openapi/docs)

## 🔐 인증 방법
1. **상단의 "Authorize" 버튼을 클릭**하여 API 키들을 입력하세요
2. 필요한 헤더 정보:
   - **appkey**: 한국투자증권에서 발급받은 앱키
   - **appsecret**: 한국투자증권에서 발급받은 앱시크릿
   - **tr_id**: API별 고유 거래ID (각 API 문서 참조)
   - **custtype**: 고객타입 (P: 개인, B: 법인)

## 🚀 사용 방법
- OAuth API는 appkey, appsecret만 필요
- 시세 조회 API는 모든 헤더 정보 필요
- WebSocket 연결 시에는 별도 접속키 발급 필요
			
 * OpenAPI spec version: 1.0.0
 */
import type { DailyPriceRequestFIDCONDMRKTDIVCODE } from './DailyPriceRequestFIDCONDMRKTDIVCODE';
import type { DailyPriceRequestFIDPERIODDIVCODE } from './DailyPriceRequestFIDPERIODDIVCODE';
import type { DailyPriceRequestFIDORGADJPRC } from './DailyPriceRequestFIDORGADJPRC';

export interface DailyPriceRequest {
  /** 조건 시장 분류 코드 */
  FID_COND_MRKT_DIV_CODE?: DailyPriceRequestFIDCONDMRKTDIVCODE;
  /**
   * 종목코드 (6자리)
   * @minLength 6
   * @maxLength 6
   */
  FID_INPUT_ISCD: string;
  /** 기간분류코드 (D:일봉, W:주봉, M:월봉) */
  FID_PERIOD_DIV_CODE?: DailyPriceRequestFIDPERIODDIVCODE;
  /** 수정주가 여부 (0:수정안함, 1:수정함) */
  FID_ORG_ADJ_PRC?: DailyPriceRequestFIDORGADJPRC;
}
