/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Korea Investment API
 * 
[OpenAPI json 링크](https://comforting-meringue-518bd8.netlify.app/swagger.json)

[API 문서 링크](https://api.koreainvestment.com/openapi/docs)

## 🔐 인증 방법
1. **상단의 "Authorize" 버튼을 클릭**하여 API 키들을 입력하세요
2. 필요한 헤더 정보:
   - **appkey**: 한국투자증권에서 발급받은 앱키
   - **appsecret**: 한국투자증권에서 발급받은 앱시크릿
   - **tr_id**: API별 고유 거래ID (각 API 문서 참조)
   - **custtype**: 고객타입 (P: 개인, B: 법인)

## 🚀 사용 방법
- OAuth API는 appkey, appsecret만 필요
- 시세 조회 API는 모든 헤더 정보 필요
- WebSocket 연결 시에는 별도 접속키 발급 필요
			
 * OpenAPI spec version: 1.0.0
 */

/**
 * 주식 상세 시세 정보
 */
export type DetailedPriceResponseOutput = {
  /** 주식 현재가 */
  stck_prpr: string;
  /** 전일 대비 */
  prdy_vrss: string;
  /** 전일 대비 부호 */
  prdy_vrss_sign: string;
  /** 전일 대비율 */
  prdy_ctrt: string;
  /** 누적 거래량 */
  acml_vol: string;
  /** 누적 거래 대금 */
  acml_tr_pbmn: string;
  /** HTS 한국어 종목명 */
  hts_kor_isnm: string;
  /** 주식 시가 */
  stck_oprc: string;
  /** 주식 고가 */
  stck_hgpr: string;
  /** 주식 저가 */
  stck_lwpr: string;
  /** 주식 상한가 */
  stck_mxpr: string;
  /** 주식 하한가 */
  stck_llam: string;
  /** 주식 기준가 */
  stck_sdpr: string;
  /** 가중평균 주식가격 */
  wghn_avrg_stck_prc: string;
  /** HTS 외국인 소진률 */
  hts_frgn_ehrt: string;
  /** 외국인 순매수 수량 */
  frgn_ntby_qty: string;
  /** 프로그램 순매수 수량 */
  pgtr_ntby_qty: string;
  /** 프라이빗 시각경매선 가격 */
  pvt_scnd_dmrs_prc: string;
  /** 프라이빗 시각매수선 가격 */
  pvt_frst_dmnd_prc: string;
  /** 프라이빗 지수 값 */
  pvt_pont_val: string;
  /** 프라이빗 시각매수선 수량 */
  pvt_frst_dmnd_qty: string;
  /** 프라이빗 시각경매선 수량 */
  pvt_scnd_dmrs_qty: string;
  /** 경매선 값 */
  dmrs_val: string;
  /** 매수선 값 */
  dmnd_val: string;
  /** 자본금 */
  cpfn: string;
  /** 제한폭 가격 */
  rstc_wdth_prc: string;
  /** 주식 액면가 */
  stck_fcam: string;
  /** 주식 대용가 */
  stck_sspr: string;
  /** 호가 단위 */
  aspr_unit: string;
  /** HTS 매매 수량 단위 값 */
  hts_deal_qty_unit_val: string;
  /** 상장 주수 */
  lstn_stcn: string;
  /** HTS 시가총액 */
  hts_avls: string;
  /** PER */
  per: string;
  /** PBR */
  pbr: string;
  /** 결산월 */
  stac_month: string;
  /** 거래량 회전율 */
  vol_tnrt: string;
  /** EPS */
  eps: string;
  /** BPS */
  bps: string;
  /** 250일 최고가 */
  d250_hgpr: string;
  /** 250일 최고가 일자 */
  d250_hgpr_date: string;
  /** 250일 최고가 대비 현재가 비율 */
  d250_hgpr_vrss_prpr_rate: string;
  /** 250일 최저가 */
  d250_lwpr: string;
  /** 250일 최저가 일자 */
  d250_lwpr_date: string;
  /** 250일 최저가 대비 현재가 비율 */
  d250_lwpr_vrss_prpr_rate: string;
  /** 주식 당년 최고가 */
  stck_dryy_hgpr: string;
  /** 당년 최고가 대비 현재가 비율 */
  dryy_hgpr_vrss_prpr_rate: string;
  /** 당년 최고가 일자 */
  dryy_hgpr_date: string;
  /** 주식 당년 최저가 */
  stck_dryy_lwpr: string;
  /** 당년 최저가 대비 현재가 비율 */
  dryy_lwpr_vrss_prpr_rate: string;
  /** 당년 최저가 일자 */
  dryy_lwpr_date: string;
  /** 52주 최고가 */
  w52_hgpr: string;
  /** 52주 최고가 대비 현재가 대비율 */
  w52_hgpr_vrss_prpr_ctrt: string;
  /** 52주 최고가 일자 */
  w52_hgpr_date: string;
  /** 52주 최저가 */
  w52_lwpr: string;
  /** 52주 최저가 대비 현재가 대비율 */
  w52_lwpr_vrss_prpr_ctrt: string;
  /** 52주 최저가 일자 */
  w52_lwpr_date: string;
  /** 전체대출잔고비율 */
  whol_loan_rmnd_rate: string;
  /** 공매도가능여부 */
  ssts_yn: string;
  /** 액면가 통화명 */
  fcam_cnnm: string;
  /** 자본금 통화명 */
  cpfn_cnnm: string;
  /** 외국인 보유 수량 */
  frgn_hldn_qty: string;
  /** VI 구분 코드 */
  vi_cls_code: string;
  /** 시간외 VI 구분 코드 */
  ovtm_vi_cls_code: string;
  /** 최종 공매도 체결 수량 */
  last_ssts_cntg_qty: string;
  /** 투자주의종목여부 */
  invt_caful_yn: string;
  /** 시장경고구분코드 */
  mrkt_warn_cls_code: string;
  /** 단기과열여부 */
  short_over_yn: string;
  /** 대주주여부 */
  sltr_yn: string;
};
