/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Korea Investment API
 * 
[OpenAPI json 링크](http://localhost:8080/swagger.json)

[API 문서 링크](https://api.koreainvestment.com/openapi/docs)

## 🔐 인증 방법
1. **상단의 "Authorize" 버튼을 클릭**하여 API 키들을 입력하세요
2. 필요한 헤더 정보:
   - **appkey**: 한국투자증권에서 발급받은 앱키
   - **appsecret**: 한국투자증권에서 발급받은 앱시크릿
   - **tr_id**: API별 고유 거래ID (각 API 문서 참조)
   - **custtype**: 고객타입 (P: 개인, B: 법인)

## 🚀 사용 방법
- OAuth API는 appkey, appsecret만 필요
- 시세 조회 API는 모든 헤더 정보 필요
- WebSocket 연결 시에는 별도 접속키 발급 필요
			
 * OpenAPI spec version: 1.0.0
 */

export type ETFComponentStockResponseOutput2Item = {
  /** 주식 단축 종목코드 */
  stck_shrn_iscd: string;
  /** HTS 한국어 종목명 */
  hts_kor_isnm: string;
  /** 주식 현재가 */
  stck_prpr: string;
  /** 전일 대비 */
  prdy_vrss: string;
  /** 전일 대비 부호 */
  prdy_vrss_sign: string;
  /** 전일 대비율 */
  prdy_ctrt: string;
  /** 누적 거래량 */
  acml_vol: string;
  /** ETF 구성비중 */
  etf_cnfg_wght: string;
  /** ETF 구성수량 */
  etf_cnfg_qty: string;
  /** ETF 구성시총 */
  etf_cnfg_avls: string;
};
