/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Korea Investment API
 * 
[OpenAPI json 링크](http://localhost:8080/swagger.json)

[API 문서 링크](https://api.koreainvestment.com/openapi/docs)

## 🔐 인증 방법
1. **상단의 "Authorize" 버튼을 클릭**하여 API 키들을 입력하세요
2. 필요한 헤더 정보:
   - **appkey**: 한국투자증권에서 발급받은 앱키
   - **appsecret**: 한국투자증권에서 발급받은 앱시크릿
   - **tr_id**: API별 고유 거래ID (각 API 문서 참조)
   - **custtype**: 고객타입 (P: 개인, B: 법인)

## 🚀 사용 방법
- OAuth API는 appkey, appsecret만 필요
- 시세 조회 API는 모든 헤더 정보 필요
- WebSocket 연결 시에는 별도 접속키 발급 필요
			
 * OpenAPI spec version: 1.0.0
 */
import type { ExpectedClosingPriceRequestFIDCONDMRKTDIVCODE } from './ExpectedClosingPriceRequestFIDCONDMRKTDIVCODE';
import type { ExpectedClosingPriceRequestFIDDIVCLSCODE } from './ExpectedClosingPriceRequestFIDDIVCLSCODE';
import type { ExpectedClosingPriceRequestFIDRANKSORTCLSCODE } from './ExpectedClosingPriceRequestFIDRANKSORTCLSCODE';

export interface ExpectedClosingPriceRequest {
  /** 조건 시장 분류 코드 */
  FID_COND_MRKT_DIV_CODE?: ExpectedClosingPriceRequestFIDCONDMRKTDIVCODE;
  /** 조건화면분류코드 */
  FID_COND_SCR_DIV_CODE?: string;
  /** 종목코드 (전체조회시 생략) */
  FID_INPUT_ISCD?: string;
  /** 분류구분코드 (0:전체, 1:특정종목) */
  FID_DIV_CLS_CODE?: ExpectedClosingPriceRequestFIDDIVCLSCODE;
  /** 순위정렬구분코드 (0:상승률순, 1:하락률순) */
  FID_RANK_SORT_CLS_CODE?: ExpectedClosingPriceRequestFIDRANKSORTCLSCODE;
}
