/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Korea Investment API
 * 
[OpenAPI json 링크](https://comforting-meringue-518bd8.netlify.app/swagger.json)

[API 문서 링크](https://api.koreainvestment.com/openapi/docs)

## 🔐 인증 방법
1. **상단의 "Authorize" 버튼을 클릭**하여 API 키들을 입력하세요
2. 필요한 헤더 정보:
   - **appkey**: 한국투자증권에서 발급받은 앱키
   - **appsecret**: 한국투자증권에서 발급받은 앱시크릿
   - **tr_id**: API별 고유 거래ID (각 API 문서 참조)
   - **custtype**: 고객타입 (P: 개인, B: 법인)

## 🚀 사용 방법
- OAuth API는 appkey, appsecret만 필요
- 시세 조회 API는 모든 헤더 정보 필요
- WebSocket 연결 시에는 별도 접속키 발급 필요
			
 * OpenAPI spec version: 1.0.0
 */

export type GetUapiDomesticStockV1QuotationsInquireTimeDailychartpriceFidPeriodDivCode = typeof GetUapiDomesticStockV1QuotationsInquireTimeDailychartpriceFidPeriodDivCode[keyof typeof GetUapiDomesticStockV1QuotationsInquireTimeDailychartpriceFidPeriodDivCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUapiDomesticStockV1QuotationsInquireTimeDailychartpriceFidPeriodDivCode = {
  NUMBER_1: '1',
  NUMBER_5: '5',
  NUMBER_10: '10',
  NUMBER_15: '15',
  NUMBER_30: '30',
  NUMBER_60: '60',
} as const;
