/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Korea Investment API
 * 
[OpenAPI json 링크](https://comforting-meringue-518bd8.netlify.app/swagger.json)

[API 문서 링크](https://api.koreainvestment.com/openapi/docs)

## 🔐 인증 방법
1. **상단의 "Authorize" 버튼을 클릭**하여 API 키들을 입력하세요
2. 필요한 헤더 정보:
   - **appkey**: 한국투자증권에서 발급받은 앱키
   - **appsecret**: 한국투자증권에서 발급받은 앱시크릿
   - **tr_id**: API별 고유 거래ID (각 API 문서 참조)
   - **custtype**: 고객타입 (P: 개인, B: 법인)

## 🚀 사용 방법
- OAuth API는 appkey, appsecret만 필요
- 시세 조회 API는 모든 헤더 정보 필요
- WebSocket 연결 시에는 별도 접속키 발급 필요
			
 * OpenAPI spec version: 1.0.0
 */

/**
 * 투자자별 매매 동향
 */
export type InvestorResponseOutput = {
  /** 외국인 보유 수량 */
  frgn_hdn_qty: string;
  /** 외국인 매도 수량 */
  frgn_sll_qty: string;
  /** 외국인 매수 수량 */
  frgn_buy_qty: string;
  /** 외국인 순매수 수량 */
  frgn_ntby_qty: string;
  /** 기관 보유 수량 */
  orgn_hdn_qty: string;
  /** 기관 매도 수량 */
  orgn_sll_qty: string;
  /** 기관 매수 수량 */
  orgn_buy_qty: string;
  /** 기관 순매수 수량 */
  orgn_ntby_qty: string;
  /** 단순합계 시가 수량 */
  sum_oprc_qty: string;
  /** 단순합계 고가 수량 */
  sum_hgpr_qty: string;
  /** 단순합계 저가 수량 */
  sum_lwpr_qty: string;
};
