/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Korea Investment API
 * 
[OpenAPI json 링크](http://localhost:8080/swagger.json)

[API 문서 링크](https://api.koreainvestment.com/openapi/docs)

## 🔐 인증 방법
1. **상단의 "Authorize" 버튼을 클릭**하여 API 키들을 입력하세요
2. 필요한 헤더 정보:
   - **appkey**: 한국투자증권에서 발급받은 앱키
   - **appsecret**: 한국투자증권에서 발급받은 앱시크릿
   - **tr_id**: API별 고유 거래ID (각 API 문서 참조)
   - **custtype**: 고객타입 (P: 개인, B: 법인)

## 🚀 사용 방법
- OAuth API는 appkey, appsecret만 필요
- 시세 조회 API는 모든 헤더 정보 필요
- WebSocket 연결 시에는 별도 접속키 발급 필요
			
 * OpenAPI spec version: 1.0.0
 */

/**
 * 시간외 호가 정보
 */
export type OvertimeAskingPriceResponseOutput = {
  /** 시간외 매도호가 1 */
  ovtm_askp1: string;
  /** 시간외 매도호가 2 */
  ovtm_askp2: string;
  /** 시간외 매도호가 3 */
  ovtm_askp3: string;
  /** 시간외 매도호가 4 */
  ovtm_askp4: string;
  /** 시간외 매도호가 5 */
  ovtm_askp5: string;
  /** 시간외 매수호가 1 */
  ovtm_bidp1: string;
  /** 시간외 매수호가 2 */
  ovtm_bidp2: string;
  /** 시간외 매수호가 3 */
  ovtm_bidp3: string;
  /** 시간외 매수호가 4 */
  ovtm_bidp4: string;
  /** 시간외 매수호가 5 */
  ovtm_bidp5: string;
  /** 시간외 매도호가 잔량 1 */
  ovtm_askp_rsqn1: string;
  /** 시간외 매도호가 잔량 2 */
  ovtm_askp_rsqn2: string;
  /** 시간외 매도호가 잔량 3 */
  ovtm_askp_rsqn3: string;
  /** 시간외 매도호가 잔량 4 */
  ovtm_askp_rsqn4: string;
  /** 시간외 매도호가 잔량 5 */
  ovtm_askp_rsqn5: string;
  /** 시간외 매수호가 잔량 1 */
  ovtm_bidp_rsqn1: string;
  /** 시간외 매수호가 잔량 2 */
  ovtm_bidp_rsqn2: string;
  /** 시간외 매수호가 잔량 3 */
  ovtm_bidp_rsqn3: string;
  /** 시간외 매수호가 잔량 4 */
  ovtm_bidp_rsqn4: string;
  /** 시간외 매수호가 잔량 5 */
  ovtm_bidp_rsqn5: string;
  /** 시간외 예상 체결가 */
  ovtm_antc_cnpr: string;
  /** 시간외 예상 거래량 */
  ovtm_antc_vol: string;
};
