/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Korea Investment API
 * 
[OpenAPI json 링크](https://comforting-meringue-518bd8.netlify.app/swagger.json)

[API 문서 링크](https://api.koreainvestment.com/openapi/docs)

## 🔐 인증 방법
1. **상단의 "Authorize" 버튼을 클릭**하여 API 키들을 입력하세요
2. 필요한 헤더 정보:
   - **appkey**: 한국투자증권에서 발급받은 앱키
   - **appsecret**: 한국투자증권에서 발급받은 앱시크릿
   - **tr_id**: API별 고유 거래ID (각 API 문서 참조)
   - **custtype**: 고객타입 (P: 개인, B: 법인)

## 🚀 사용 방법
- OAuth API는 appkey, appsecret만 필요
- 시세 조회 API는 모든 헤더 정보 필요
- WebSocket 연결 시에는 별도 접속키 발급 필요
			
 * OpenAPI spec version: 1.0.0
 */

/**
 * 시간외 현재가 정보
 */
export type OvertimePriceResponseOutput = {
  /** 주식 단축 종목코드 */
  stck_shrn_iscd: string;
  /** 주식 현재가 */
  stck_prpr: string;
  /** 전일 대비 */
  prdy_vrss: string;
  /** 전일 대비 부호 */
  prdy_vrss_sign: string;
  /** 전일 대비율 */
  prdy_ctrt: string;
  /** 누적 거래량 */
  acml_vol: string;
  /** 누적 거래 대금 */
  acml_tr_pbmn: string;
  /** HTS 한국어 종목명 */
  hts_kor_isnm: string;
  /** 주식 시가 */
  stck_oprc: string;
  /** 주식 고가 */
  stck_hgpr: string;
  /** 주식 저가 */
  stck_lwpr: string;
  /** 주식 상한가 */
  stck_mxpr: string;
  /** 주식 하한가 */
  stck_llam: string;
  /** 주식 전일 종가 */
  stck_prdy_clpr: string;
  /** 매도호가 잔량 1 */
  askp_rsqn1: string;
  /** 매도호가 잔량 2 */
  askp_rsqn2: string;
  /** 매도호가 잔량 3 */
  askp_rsqn3: string;
  /** 매도호가 잔량 4 */
  askp_rsqn4: string;
  /** 매도호가 잔량 5 */
  askp_rsqn5: string;
  /** 매수호가 잔량 1 */
  bidp_rsqn1: string;
  /** 매수호가 잔량 2 */
  bidp_rsqn2: string;
  /** 매수호가 잔량 3 */
  bidp_rsqn3: string;
  /** 매수호가 잔량 4 */
  bidp_rsqn4: string;
  /** 매수호가 잔량 5 */
  bidp_rsqn5: string;
  /** 매도호가 1 */
  askp1: string;
  /** 매도호가 2 */
  askp2: string;
  /** 매도호가 3 */
  askp3: string;
  /** 매도호가 4 */
  askp4: string;
  /** 매도호가 5 */
  askp5: string;
  /** 매수호가 1 */
  bidp1: string;
  /** 매수호가 2 */
  bidp2: string;
  /** 매수호가 3 */
  bidp3: string;
  /** 매수호가 4 */
  bidp4: string;
  /** 매수호가 5 */
  bidp5: string;
  /** 예상 체결가 */
  antc_cnpr: string;
  /** 예상 체결 대비 */
  antc_cntg_vrss: string;
  /** 예상 체결 대비 부호 */
  antc_cntg_vrss_sign: string;
  /** 예상 체결 전일 대비율 */
  antc_cntg_prdy_ctrt: string;
  /** 예상 거래량 */
  antc_vol: string;
  /** 주식 액면가 */
  stck_fcam: string;
  /** 주식 대용가 */
  stck_sspr: string;
  /** 호가 단위 */
  aspr_unit: string;
  /** HTS 매매 수량 단위 값 */
  hts_deal_qty_unit_val: string;
  /** 상장 주수 */
  lstn_stcn: string;
  /** HTS 시가총액 */
  hts_avls: string;
  /** PER */
  per: string;
  /** PBR */
  pbr: string;
  /** 결산월 */
  stac_month: string;
  /** 거래량 회전율 */
  vol_tnrt: string;
  /** EPS */
  eps: string;
  /** BPS */
  bps: string;
  /** 250일 최고가 */
  d250_hgpr: string;
  /** 250일 최고가 일자 */
  d250_hgpr_date: string;
  /** 250일 최고가 대비 현재가 비율 */
  d250_hgpr_vrss_prpr_rate: string;
  /** 250일 최저가 */
  d250_lwpr: string;
  /** 250일 최저가 일자 */
  d250_lwpr_date: string;
  /** 250일 최저가 대비 현재가 비율 */
  d250_lwpr_vrss_prpr_rate: string;
  /** 주식 당년 최고가 */
  stck_dryy_hgpr: string;
  /** 당년 최고가 대비 현재가 비율 */
  dryy_hgpr_vrss_prpr_rate: string;
  /** 당년 최고가 일자 */
  dryy_hgpr_date: string;
  /** 주식 당년 최저가 */
  stck_dryy_lwpr: string;
  /** 당년 최저가 대비 현재가 비율 */
  dryy_lwpr_vrss_prpr_rate: string;
  /** 당년 최저가 일자 */
  dryy_lwpr_date: string;
  /** 52주 최고가 */
  w52_hgpr: string;
  /** 52주 최고가 대비 현재가 대비율 */
  w52_hgpr_vrss_prpr_ctrt: string;
  /** 52주 최고가 일자 */
  w52_hgpr_date: string;
  /** 52주 최저가 */
  w52_lwpr: string;
  /** 52주 최저가 대비 현재가 대비율 */
  w52_lwpr_vrss_prpr_ctrt: string;
  /** 52주 최저가 일자 */
  w52_lwpr_date: string;
  /** 전체대출잔고비율 */
  whol_loan_rmnd_rate: string;
  /** 공매도가능여부 */
  ssts_yn: string;
  /** 액면가 통화명 */
  fcam_cnnm: string;
  /** 자본금 통화명 */
  cpfn_cnnm: string;
  /** 외국인 보유 수량 */
  frgn_hldn_qty: string;
  /** VI 구분 코드 */
  vi_cls_code: string;
  /** 시간외 VI 구분 코드 */
  ovtm_vi_cls_code: string;
  /** 최종 공매도 체결 수량 */
  last_ssts_cntg_qty: string;
  /** 투자주의종목여부 */
  invt_caful_yn: string;
  /** 시장경고구분코드 */
  mrkt_warn_cls_code: string;
  /** 단기과열여부 */
  short_over_yn: string;
  /** 대주주여부 */
  sltr_yn: string;
};
