import { OpenAPIRegistry } from "@asteasolutions/zod-to-openapi";
import express, { type Router } from "express";
import { z } from "zod";
import { createApiResponse } from "@/api-docs/openAPIResponseBuilders";

// Extend Zod with OpenAPI
import { extendZodWithOpenApi } from "@asteasolutions/zod-to-openapi";
extendZodWithOpenApi(z);

export const domesticQuotationsRegistry = new OpenAPIRegistry();
export const domesticQuotationsRouter: Router = express.Router();

// 주식현재가 시세 (가장 많이 사용하는 API)
domesticQuotationsRegistry.registerPath({
  method: "get",
  path: "/uapi/domestic-stock/v1/quotations/inquire-price",
  tags: ["국내주식 기본시세"],
  summary: "주식현재가 시세",
  description: `국내주식의 현재가 시세 정보를 조회합니다

**TR_ID:** FHKST01010100 (실전/모의 동일)`,
  security: [{ bearerAuth: [] }],
  request: {
    query: z.object({
      FID_COND_MRKT_DIV_CODE: z.enum(["J"]).default("J").describe("조건 시장 분류 코드 (J: 주식)"),
      FID_INPUT_ISCD: z.string().min(6).max(6).describe("종목코드 (6자리, 예: 005930)"),
    }),
    headers: z.object({
      appkey: z.string().describe("앱키"),
      appsecret: z.string().describe("앱시크릿"),
      tr_id: z.string().default("FHKST01010100").describe("거래ID"),
      custtype: z.enum(["P", "B"]).default("P").describe("고객타입 (P:개인, B:법인)"),
    }),
  },
  responses: createApiResponse(z.object({
    rt_cd: z.string().describe("성공 실패 여부 (0:성공)"),
    msg_cd: z.string().describe("응답코드"),
    msg1: z.string().describe("응답메세지"),
    output: z.object({
      iscd_stat_cls_code: z.string().describe("종목 상태 구분 코드"),
      marg_rate: z.string().describe("증거금 비율"),
      rprs_mrkt_kor_name: z.string().describe("대표시장 한글명"),
      bstp_kor_isnm: z.string().describe("업종 한글 종목명"),
      temp_stop_yn: z.string().describe("임시정지 여부"),
      oprc_rang_cont_yn: z.string().describe("가격 범위 연장 여부"),
      stck_prpr: z.string().describe("주식 현재가"),
      stck_shrn_iscd: z.string().describe("주식 단축 종목코드"),
      prdy_vrss: z.string().describe("전일 대비"),
      prdy_vrss_sign: z.string().describe("전일 대비 부호"),
      prdy_ctrt: z.string().describe("전일 대비율"),
      acml_vol: z.string().describe("누적 거래량"),
      stck_oprc: z.string().describe("주식 시가"),
      stck_hgpr: z.string().describe("주식 고가"),
      stck_lwpr: z.string().describe("주식 저가"),
      stck_mxpr: z.string().describe("주식 상한가"),
      stck_llam: z.string().describe("주식 하한가"),
    }).describe("응답 상세"),
  }), "주식 현재가 조회 성공"),
});

// 호가/예상체결
domesticQuotationsRegistry.registerPath({
  method: "get",
  path: "/uapi/domestic-stock/v1/quotations/inquire-asking-price-exp-ccn",
  tags: ["국내주식 기본시세"],
  summary: "주식현재가 호가/예상체결",
  description: "주식의 호가 정보와 예상체결 정보를 조회합니다 (TR_ID: FHKST01010200)",
  security: [{ bearerAuth: [] }],
  request: {
    query: z.object({
      FID_COND_MRKT_DIV_CODE: z.enum(["J"]).default("J").describe("조건 시장 분류 코드"),
      FID_INPUT_ISCD: z.string().min(6).max(6).describe("종목코드 (6자리)"),
    }),
    headers: z.object({
      appkey: z.string().describe("앱키"),
      appsecret: z.string().describe("앱시크릿"),
      tr_id: z.string().default("FHKST01010200").describe("거래ID"),
      custtype: z.enum(["P", "B"]).default("P").describe("고객타입"),
    }),
  },
  responses: createApiResponse(z.object({
    rt_cd: z.string().describe("성공 실패 여부"),
    msg_cd: z.string().describe("응답코드"),
    msg1: z.string().describe("응답메세지"),
    output1: z.object({
      stck_prpr: z.string().describe("주식 현재가"),
      stck_oprc: z.string().describe("주식 시가"),
      stck_hgpr: z.string().describe("주식 고가"),
      stck_lwpr: z.string().describe("주식 저가"),
      askp1: z.string().describe("매도호가1"),
      askp2: z.string().describe("매도호가2"),
      askp3: z.string().describe("매도호가3"),
      askp4: z.string().describe("매도호가4"),
      askp5: z.string().describe("매도호가5"),
      bidp1: z.string().describe("매수호가1"),
      bidp2: z.string().describe("매수호가2"),
      bidp3: z.string().describe("매수호가3"),
      bidp4: z.string().describe("매수호가4"),
      bidp5: z.string().describe("매수호가5"),
    }).describe("호가 정보"),
    output2: z.object({
      antc_cnpr: z.string().describe("예상 체결가"),
      antc_cntg_vrss: z.string().describe("예상 체결 대비"),
      antc_cntg_vrss_sign: z.string().describe("예상 체결 대비 부호"),
      antc_cntg_prdy_ctrt: z.string().describe("예상 체결 전일 대비율"),
      antc_vol: z.string().describe("예상 거래량"),
    }).describe("예상체결 정보"),
  }), "호가/예상체결 조회 성공"),
});

// 일별시세
domesticQuotationsRegistry.registerPath({
  method: "get",
  path: "/uapi/domestic-stock/v1/quotations/inquire-daily-price",
  tags: ["국내주식 기본시세"],
  summary: "주식현재가 일자별",
  description: "주식의 일자별 시세 정보를 조회합니다 (TR_ID: FHKST01010400)",
  security: [{ bearerAuth: [] }],
  request: {
    query: z.object({
      FID_COND_MRKT_DIV_CODE: z.enum(["J"]).default("J").describe("조건 시장 분류 코드"),
      FID_INPUT_ISCD: z.string().min(6).max(6).describe("종목코드 (6자리)"),
      FID_PERIOD_DIV_CODE: z.enum(["D", "W", "M"]).default("D").describe("기간분류코드 (D:일봉, W:주봉, M:월봉)"),
      FID_ORG_ADJ_PRC: z.enum(["0", "1"]).default("0").describe("수정주가 여부 (0:수정안함, 1:수정함)"),
    }),
    headers: z.object({
      appkey: z.string().describe("앱키"),
      appsecret: z.string().describe("앱시크릿"),
      tr_id: z.string().default("FHKST01010400").describe("거래ID"),
      custtype: z.enum(["P", "B"]).default("P").describe("고객타입"),
    }),
  },
  responses: createApiResponse(z.object({
    rt_cd: z.string().describe("성공 실패 여부"),
    msg_cd: z.string().describe("응답코드"),
    msg1: z.string().describe("응답메세지"),
    output: z.array(z.object({
      stck_bsop_date: z.string().describe("주식 영업 일자"),
      stck_oprc: z.string().describe("주식 시가"),
      stck_hgpr: z.string().describe("주식 고가"),
      stck_lwpr: z.string().describe("주식 저가"),
      stck_clpr: z.string().describe("주식 종가"),
      acml_vol: z.string().describe("누적 거래량"),
      acml_tr_pbmn: z.string().describe("누적 거래 대금"),
      flng_cls_code: z.string().describe("락 구분 코드"),
      prtt_rate: z.string().describe("분할 비율"),
      mod_yn: z.string().describe("분할변경여부"),
      prdy_vrss_sign: z.string().describe("전일 대비 부호"),
      prdy_vrss: z.string().describe("전일 대비"),
      revl_issu_reas: z.string().describe("재평가사유"),
    })).describe("일별시세 목록"),
  }), "일별시세 조회 성공"),
});

// 주식현재가 체결
domesticQuotationsRegistry.registerPath({
  method: "get",
  path: "/uapi/domestic-stock/v1/quotations/inquire-ccnl",
  tags: ["국내주식 기본시세"],
  summary: "주식현재가 체결",
  description: "주식의 체결 내역 정보를 조회합니다 (TR_ID: FHKST01010300)",
  security: [{ bearerAuth: [] }],
  request: {
    query: z.object({
      FID_COND_MRKT_DIV_CODE: z.enum(["J"]).default("J").describe("조건 시장 분류 코드"),
      FID_INPUT_ISCD: z.string().min(6).max(6).describe("종목코드 (6자리)"),
    }),
    headers: z.object({
      appkey: z.string().describe("앱키"),
      appsecret: z.string().describe("앱시크릿"),
      tr_id: z.string().default("FHKST01010300").describe("거래ID"),
      custtype: z.enum(["P", "B"]).default("P").describe("고객타입"),
    }),
  },
  responses: createApiResponse(z.object({
    rt_cd: z.string().describe("성공 실패 여부"),
    msg_cd: z.string().describe("응답코드"),
    msg1: z.string().describe("응답메세지"),
    output: z.array(z.object({
      stck_cntg_hour: z.string().describe("주식 체결 시간"),
      stck_prpr: z.string().describe("주식 현재가"),
      prdy_vrss: z.string().describe("전일 대비"),
      prdy_vrss_sign: z.string().describe("전일 대비 부호"),
      cntg_vol: z.string().describe("체결 거래량"),
      tday_rltv: z.string().describe("당일 체결 강도"),
      prdy_ctrt: z.string().describe("전일 대비율"),
    })).describe("체결 내역 목록"),
  }), "주식 체결 조회 성공"),
});

// 주식현재가 투자자
domesticQuotationsRegistry.registerPath({
  method: "get",
  path: "/uapi/domestic-stock/v1/quotations/inquire-investor",
  tags: ["국내주식 기본시세"],
  summary: "주식현재가 투자자",
  description: "주식의 투자자별 매매 동향을 조회합니다 (TR_ID: FHKST01010900)",
  security: [{ bearerAuth: [] }],
  request: {
    query: z.object({
      FID_COND_MRKT_DIV_CODE: z.enum(["J"]).default("J").describe("조건 시장 분류 코드"),
      FID_INPUT_ISCD: z.string().min(6).max(6).describe("종목코드 (6자리)"),
    }),
    headers: z.object({
      appkey: z.string().describe("앱키"),
      appsecret: z.string().describe("앱시크릿"),
      tr_id: z.string().default("FHKST01010900").describe("거래ID"),
      custtype: z.enum(["P", "B"]).default("P").describe("고객타입"),
    }),
  },
  responses: createApiResponse(z.object({
    rt_cd: z.string().describe("성공 실패 여부"),
    msg_cd: z.string().describe("응답코드"),
    msg1: z.string().describe("응답메세지"),
    output: z.object({
      frgn_hdn_qty: z.string().describe("외국인 보유 수량"),
      frgn_sll_qty: z.string().describe("외국인 매도 수량"),
      frgn_buy_qty: z.string().describe("외국인 매수 수량"),
      frgn_ntby_qty: z.string().describe("외국인 순매수 수량"),
      orgn_hdn_qty: z.string().describe("기관 보유 수량"),
      orgn_sll_qty: z.string().describe("기관 매도 수량"),
      orgn_buy_qty: z.string().describe("기관 매수 수량"),
      orgn_ntby_qty: z.string().describe("기관 순매수 수량"),
      sum_oprc_qty: z.string().describe("단순합계 시가 수량"),
      sum_hgpr_qty: z.string().describe("단순합계 고가 수량"),
      sum_lwpr_qty: z.string().describe("단순합계 저가 수량"),
    }).describe("투자자별 매매 동향"),
  }), "투자자 매매동향 조회 성공"),
});

// 주식현재가 회원사
domesticQuotationsRegistry.registerPath({
  method: "get",
  path: "/uapi/domestic-stock/v1/quotations/inquire-member",
  tags: ["국내주식 기본시세"],
  summary: "주식현재가 회원사",
  description: "주식의 회원사별 매매 동향을 조회합니다 (TR_ID: FHKST01010600)",
  security: [{ bearerAuth: [] }],
  request: {
    query: z.object({
      FID_COND_MRKT_DIV_CODE: z.enum(["J"]).default("J").describe("조건 시장 분류 코드"),
      FID_INPUT_ISCD: z.string().min(6).max(6).describe("종목코드 (6자리)"),
    }),
    headers: z.object({
      appkey: z.string().describe("앱키"),
      appsecret: z.string().describe("앱시크릿"),
      tr_id: z.string().default("FHKST01010600").describe("거래ID"),
      custtype: z.enum(["P", "B"]).default("P").describe("고객타입"),
    }),
  },
  responses: createApiResponse(z.object({
    rt_cd: z.string().describe("성공 실패 여부"),
    msg_cd: z.string().describe("응답코드"),
    msg1: z.string().describe("응답메세지"),
    output: z.array(z.object({
      mbcr_name: z.string().describe("회원사명"),
      sll_qty: z.string().describe("매도 수량"),
      buy_qty: z.string().describe("매수 수량"),
      ntby_qty: z.string().describe("순매수 수량"),
      sll_amt: z.string().describe("매도 금액"),
      buy_amt: z.string().describe("매수 금액"),
      ntby_amt: z.string().describe("순매수 금액"),
    })).describe("회원사별 매매 동향"),
  }), "회원사 매매동향 조회 성공"),
});

// 주식현재가 시세 2
domesticQuotationsRegistry.registerPath({
  method: "get",
  path: "/uapi/domestic-stock/v1/quotations/inquire-price-2",
  tags: ["국내죝식 기본시세"],
  summary: "주식현재가 시세 2",
  description: "주식의 추가 시세 정보를 조회합니다 (TR_ID: FHPST01010000)",
  security: [{ bearerAuth: [] }],
  request: {
    query: z.object({
      FID_COND_MRKT_DIV_CODE: z.enum(["J"]).default("J").describe("조건 시장 분류 코드"),
      FID_INPUT_ISCD: z.string().min(6).max(6).describe("종목코드 (6자리)"),
    }),
    headers: z.object({
      appkey: z.string().describe("앱키"),
      appsecret: z.string().describe("앱시크릿"),
      tr_id: z.string().default("FHPST01010000").describe("거래ID"),
      custtype: z.enum(["P", "B"]).default("P").describe("고객타입"),
    }),
  },
  responses: createApiResponse(z.object({
    rt_cd: z.string().describe("성공 실패 여부"),
    msg_cd: z.string().describe("응답코드"),
    msg1: z.string().describe("응답메세지"),
    output: z.object({
      stck_prpr: z.string().describe("주식 현재가"),
      prdy_vrss: z.string().describe("전일 대비"),
      prdy_vrss_sign: z.string().describe("전일 대비 부호"),
      prdy_ctrt: z.string().describe("전일 대비율"),
      acml_vol: z.string().describe("누적 거래량"),
      acml_tr_pbmn: z.string().describe("누적 거래 대금"),
      hts_kor_isnm: z.string().describe("HTS 한국어 종목명"),
      stck_oprc: z.string().describe("주식 시가"),
      stck_hgpr: z.string().describe("주식 고가"),
      stck_lwpr: z.string().describe("주식 저가"),
      stck_mxpr: z.string().describe("죝식 상한가"),
      stck_llam: z.string().describe("죽식 하한가"),
      stck_sdpr: z.string().describe("죽식 기준가"),
      wghn_avrg_stck_prc: z.string().describe("가중평균 죽식가격"),
      hts_frgn_ehrt: z.string().describe("HTS 외국인 소진률"),
      frgn_ntby_qty: z.string().describe("외국인 순매수 수량"),
      pgtr_ntby_qty: z.string().describe("프로그램 순매수 수량"),
      pvt_scnd_dmrs_prc: z.string().describe("프라이빗 시각경매선 가격"),
      pvt_frst_dmnd_prc: z.string().describe("프라이빗 시각매수선 가격"),
      pvt_pont_val: z.string().describe("프라이빗 지수 값"),
      pvt_frst_dmnd_qty: z.string().describe("프라이빗 시각매수선 수량"),
      pvt_scnd_dmrs_qty: z.string().describe("프라이빗 시각경매선 수량"),
      dmrs_val: z.string().describe("경매선 값"),
      dmnd_val: z.string().describe("매수선 값"),
      cpfn: z.string().describe("자본금"),
      rstc_wdth_prc: z.string().describe("제한폭 가격"),
      stck_fcam: z.string().describe("죽식 액면가"),
      stck_sspr: z.string().describe("죽식 대용가"),
      aspr_unit: z.string().describe("호가 단위"),
      hts_deal_qty_unit_val: z.string().describe("HTS 매매 수량 단위 값"),
      lstn_stcn: z.string().describe("상장 주수"),
      hts_avls: z.string().describe("HTS 시가총액"),
      per: z.string().describe("PER"),
      pbr: z.string().describe("PBR"),
      stac_month: z.string().describe("결산월"),
      vol_tnrt: z.string().describe("거래량 회전율"),
      eps: z.string().describe("EPS"),
      bps: z.string().describe("BPS"),
      d250_hgpr: z.string().describe("250일 최고가"),
      d250_hgpr_date: z.string().describe("250일 최고가 일자"),
      d250_hgpr_vrss_prpr_rate: z.string().describe("250일 최고가 대비 현재가 비율"),
      d250_lwpr: z.string().describe("250일 최저가"),
      d250_lwpr_date: z.string().describe("250일 최저가 일자"),
      d250_lwpr_vrss_prpr_rate: z.string().describe("250일 최저가 대비 현재가 비율"),
      stck_dryy_hgpr: z.string().describe("죽식 당년 최고가"),
      dryy_hgpr_vrss_prpr_rate: z.string().describe("당년 최고가 대비 현재가 비율"),
      dryy_hgpr_date: z.string().describe("당년 최고가 일자"),
      stck_dryy_lwpr: z.string().describe("죽식 당년 최저가"),
      dryy_lwpr_vrss_prpr_rate: z.string().describe("당년 최저가 대비 현재가 비율"),
      dryy_lwpr_date: z.string().describe("당년 최저가 일자"),
      w52_hgpr: z.string().describe("52주 최고가"),
      w52_hgpr_vrss_prpr_ctrt: z.string().describe("52주 최고가 대비 현재가 대비율"),
      w52_hgpr_date: z.string().describe("52주 최고가 일자"),
      w52_lwpr: z.string().describe("52주 최저가"),
      w52_lwpr_vrss_prpr_ctrt: z.string().describe("52주 최저가 대비 현재가 대비율"),
      w52_lwpr_date: z.string().describe("52주 최저가 일자"),
      whol_loan_rmnd_rate: z.string().describe("전체대출잔고비율"),
      ssts_yn: z.string().describe("공매도가능여부"),
      fcam_cnnm: z.string().describe("액면가 통화명"),
      cpfn_cnnm: z.string().describe("자본금 통화명"),
      frgn_hldn_qty: z.string().describe("외국인 보유 수량"),
      vi_cls_code: z.string().describe("VI 구분 코드"),
      ovtm_vi_cls_code: z.string().describe("시간외 VI 구분 코드"),
      last_ssts_cntg_qty: z.string().describe("최종 공매도 체결 수량"),
      invt_caful_yn: z.string().describe("투자주의종목여부"),
      mrkt_warn_cls_code: z.string().describe("시장경고구분코드"),
      short_over_yn: z.string().describe("단기과열여부"),
      sltr_yn: z.string().describe("대주주여부"),
    }).describe("죝식 상세 시세 정보"),
  }), "죽식 시세 2 조회 성공"),
});

// 국내죽식 기간별시세(일/주/월/년)
domesticQuotationsRegistry.registerPath({
  method: "get",
  path: "/uapi/domestic-stock/v1/quotations/inquire-daily-itemchartprice",
  tags: ["국내죽식 기본시세"],
  summary: "국내죽식기간별시세(일/주/월/년)",
  description: "죽식의 기간별 차트 데이터를 조회합니다 (TR_ID: FHKST03010100)",
  security: [{ bearerAuth: [] }],
  request: {
    query: z.object({
      FID_COND_MRKT_DIV_CODE: z.enum(["J"]).default("J").describe("조건 시장 분류 코드"),
      FID_INPUT_ISCD: z.string().min(6).max(6).describe("종목코드 (6자리)"),
      FID_INPUT_DATE_1: z.string().describe("시작일자 (YYYYMMDD)"),
      FID_INPUT_DATE_2: z.string().describe("종료일자 (YYYYMMDD)"),
      FID_PERIOD_DIV_CODE: z.enum(["D", "W", "M", "Y"]).describe("기간분류코드 (D:일봉, W:주봉, M:월봉, Y:년봉)"),
      FID_ORG_ADJ_PRC: z.enum(["0", "1"]).default("0").describe("수정죽가 여부 (0:수정안함, 1:수정함)"),
    }),
    headers: z.object({
      appkey: z.string().describe("앱키"),
      appsecret: z.string().describe("앱시크릿"),
      tr_id: z.string().default("FHKST03010100").describe("거래ID"),
      custtype: z.enum(["P", "B"]).default("P").describe("고객타입"),
    }),
  },
  responses: createApiResponse(z.object({
    rt_cd: z.string().describe("성공 실패 여부"),
    msg_cd: z.string().describe("응답코드"),
    msg1: z.string().describe("응답메세지"),
    output1: z.object({
      prdy_vrss: z.string().describe("전일 대비"),
      prdy_vrss_sign: z.string().describe("전일 대비 부호"),
      prdy_ctrt: z.string().describe("전일 대비율"),
      stck_prdy_clpr: z.string().describe("죽식 전일 종가"),
      acml_vol: z.string().describe("누적 거래량"),
      acml_tr_pbmn: z.string().describe("누적 거래 대금"),
      hts_kor_isnm: z.string().describe("HTS 한국어 종목명"),
      stck_prpr: z.string().describe("죽식 현재가"),
      stck_shrn_iscd: z.string().describe("죽식 단축 종목코드"),
      prdy_vol: z.string().describe("전일 거래량"),
    }).describe("기간별 시세 요약"),
    output2: z.array(z.object({
      stck_bsop_date: z.string().describe("죽식 영업 일자"),
      stck_clpr: z.string().describe("죽식 종가"),
      stck_oprc: z.string().describe("죽식 시가"),
      stck_hgpr: z.string().describe("죽식 고가"),
      stck_lwpr: z.string().describe("죽식 저가"),
      acml_vol: z.string().describe("누적 거래량"),
      acml_tr_pbmn: z.string().describe("누적 거래 대금"),
      flng_cls_code: z.string().describe("락 구분 코드"),
      prtt_rate: z.string().describe("분할 비율"),
      mod_yn: z.string().describe("분할변경여부"),
      prdy_vrss_sign: z.string().describe("전일 대비 부호"),
      prdy_vrss: z.string().describe("전일 대비"),
      revl_issu_reas: z.string().describe("재평가사유"),
    })).describe("기간별 시세 목록"),
  }), "기간별 시세 조회 성공"),
});

// 죽식당일분봉조회
domesticQuotationsRegistry.registerPath({
  method: "get",
  path: "/uapi/domestic-stock/v1/quotations/inquire-time-itemchartprice",
  tags: ["국내죽식 기본시세"],
  summary: "죽식당일분봉조회",
  description: "죽식의 당일 분봉 차트 데이터를 조회합니다 (TR_ID: FHKST03010200)",
  security: [{ bearerAuth: [] }],
  request: {
    query: z.object({
      FID_COND_MRKT_DIV_CODE: z.enum(["J"]).default("J").describe("조건 시장 분류 코드"),
      FID_INPUT_ISCD: z.string().min(6).max(6).describe("종목코드 (6자리)"),
      FID_INPUT_HOUR_1: z.string().describe("시작시간 (HHMMSS)"),
      FID_PW_DATA_INCU_YN: z.enum(["Y", "N"]).default("Y").describe("과거 데이터 포함 여부"),
    }),
    headers: z.object({
      appkey: z.string().describe("앱키"),
      appsecret: z.string().describe("앱시크릿"),
      tr_id: z.string().default("FHKST03010200").describe("거래ID"),
      custtype: z.enum(["P", "B"]).default("P").describe("고객타입"),
    }),
  },
  responses: createApiResponse(z.object({
    rt_cd: z.string().describe("성공 실패 여부"),
    msg_cd: z.string().describe("응답코드"),
    msg1: z.string().describe("응답메세지"),
    output1: z.object({
      prdy_vrss: z.string().describe("전일 대비"),
      prdy_vrss_sign: z.string().describe("전일 대비 부호"),
      prdy_ctrt: z.string().describe("전일 대비율"),
      stck_prdy_clpr: z.string().describe("죽식 전일 종가"),
      acml_vol: z.string().describe("누적 거래량"),
      acml_tr_pbmn: z.string().describe("누적 거래 대금"),
      hts_kor_isnm: z.string().describe("HTS 한국어 종목명"),
      stck_prpr: z.string().describe("죽식 현재가"),
      stck_shrn_iscd: z.string().describe("죽식 단축 종목코드"),
    }).describe("당일 분봉 요약"),
    output2: z.array(z.object({
      stck_bsop_date: z.string().describe("죽식 영업 일자"),
      stck_cntg_hour: z.string().describe("죽식 체결 시간"),
      stck_prpr: z.string().describe("죽식 현재가"),
      stck_oprc: z.string().describe("죽식 시가"),
      stck_hgpr: z.string().describe("죽식 고가"),
      stck_lwpr: z.string().describe("죽식 저가"),
      cntg_vol: z.string().describe("체결 거래량"),
      acml_tr_pbmn: z.string().describe("누적 거래 대금"),
    })).describe("당일 분봉 목록"),
  }), "당일 분봉 조회 성공"),
});

// 죽식현재가 당일시간대별체결
domesticQuotationsRegistry.registerPath({
  method: "get",
  path: "/uapi/domestic-stock/v1/quotations/inquire-time-itemconclusion",
  tags: ["국내죽식 기본시세"],
  summary: "죽식현재가 당일시간대별체결",
  description: "죽식의 시간대별 체결 내역을 조회합니다 (TR_ID: FHPST01060000)",
  security: [{ bearerAuth: [] }],
  request: {
    query: z.object({
      FID_COND_MRKT_DIV_CODE: z.enum(["J"]).default("J").describe("조건 시장 분류 코드"),
      FID_INPUT_ISCD: z.string().min(6).max(6).describe("종목코드 (6자리)"),
      FID_INPUT_HOUR_1: z.string().describe("시작시간 (HHMMSS)"),
      FID_INPUT_HOUR_2: z.string().describe("종료시간 (HHMMSS)"),
    }),
    headers: z.object({
      appkey: z.string().describe("앱키"),
      appsecret: z.string().describe("앱시크릿"),
      tr_id: z.string().default("FHPST01060000").describe("거래ID"),
      custtype: z.enum(["P", "B"]).default("P").describe("고객타입"),
    }),
  },
  responses: createApiResponse(z.object({
    rt_cd: z.string().describe("성공 실패 여부"),
    msg_cd: z.string().describe("응답코드"),
    msg1: z.string().describe("응답메세지"),
    output: z.array(z.object({
      stck_cntg_hour: z.string().describe("죽식 체결 시간"),
      stck_prpr: z.string().describe("죽식 현재가"),
      prdy_vrss: z.string().describe("전일 대비"),
      prdy_vrss_sign: z.string().describe("전일 대비 부호"),
      cntg_vol: z.string().describe("체결 거래량"),
      tday_rltv: z.string().describe("당일 체결강도"),
      prdy_ctrt: z.string().describe("전일 대비율"),
    })).describe("시간대별 체결 내역"),
  }), "시간대별 체결 조회 성공"),
});

// 국내죽식 시간외현재가
domesticQuotationsRegistry.registerPath({
  method: "get",
  path: "/uapi/domestic-stock/v1/quotations/inquire-overtime-price",
  tags: ["국내죽식 기본시세"],
  summary: "국내죽식 시간외현재가",
  description: "죽식의 시간외 현재가 정보를 조회합니다 (TR_ID: FHPST02300000)",
  security: [{ bearerAuth: [] }],
  request: {
    query: z.object({
      FID_COND_MRKT_DIV_CODE: z.enum(["J"]).default("J").describe("조건 시장 분류 코드"),
      FID_INPUT_ISCD: z.string().min(6).max(6).describe("종목코드 (6자리)"),
    }),
    headers: z.object({
      appkey: z.string().describe("앱키"),
      appsecret: z.string().describe("앱시크릿"),
      tr_id: z.string().default("FHPST02300000").describe("거래ID"),
      custtype: z.enum(["P", "B"]).default("P").describe("고객타입"),
    }),
  },
  responses: createApiResponse(z.object({
    rt_cd: z.string().describe("성공 실패 여부"),
    msg_cd: z.string().describe("응답코드"),
    msg1: z.string().describe("응답메세지"),
    output: z.object({
      stck_shrn_iscd: z.string().describe("죽식 단축 종목코드"),
      stck_prpr: z.string().describe("죽식 현재가"),
      prdy_vrss: z.string().describe("전일 대비"),
      prdy_vrss_sign: z.string().describe("전일 대비 부호"),
      prdy_ctrt: z.string().describe("전일 대비율"),
      acml_vol: z.string().describe("누적 거래량"),
      acml_tr_pbmn: z.string().describe("누적 거래 대금"),
      hts_kor_isnm: z.string().describe("HTS 한국어 종목명"),
      stck_oprc: z.string().describe("죽식 시가"),
      stck_hgpr: z.string().describe("죽식 고가"),
      stck_lwpr: z.string().describe("죽식 저가"),
      stck_mxpr: z.string().describe("죽식 상한가"),
      stck_llam: z.string().describe("죽식 하한가"),
      stck_prdy_clpr: z.string().describe("죽식 전일 종가"),
      askp_rsqn1: z.string().describe("매도호가 잔량 1"),
      askp_rsqn2: z.string().describe("매도호가 잔량 2"),
      askp_rsqn3: z.string().describe("매도호가 잔량 3"),
      askp_rsqn4: z.string().describe("매도호가 잔량 4"),
      askp_rsqn5: z.string().describe("매도호가 잔량 5"),
      bidp_rsqn1: z.string().describe("매수호가 잔량 1"),
      bidp_rsqn2: z.string().describe("매수호가 잔량 2"),
      bidp_rsqn3: z.string().describe("매수호가 잔량 3"),
      bidp_rsqn4: z.string().describe("매수호가 잔량 4"),
      bidp_rsqn5: z.string().describe("매수호가 잔량 5"),
      askp1: z.string().describe("매도호가 1"),
      askp2: z.string().describe("매도호가 2"),
      askp3: z.string().describe("매도호가 3"),
      askp4: z.string().describe("매도호가 4"),
      askp5: z.string().describe("매도호가 5"),
      bidp1: z.string().describe("매수호가 1"),
      bidp2: z.string().describe("매수호가 2"),
      bidp3: z.string().describe("매수호가 3"),
      bidp4: z.string().describe("매수호가 4"),
      bidp5: z.string().describe("매수호가 5"),
      antc_cnpr: z.string().describe("예상 체결가"),
      antc_cntg_vrss: z.string().describe("예상 체결 대비"),
      antc_cntg_vrss_sign: z.string().describe("예상 체결 대비 부호"),
      antc_cntg_prdy_ctrt: z.string().describe("예상 체결 전일 대비율"),
      antc_vol: z.string().describe("예상 거래량"),
      stck_fcam: z.string().describe("죽식 액면가"),
      stck_sspr: z.string().describe("죽식 대용가"),
      aspr_unit: z.string().describe("호가 단위"),
      hts_deal_qty_unit_val: z.string().describe("HTS 매매 수량 단위 값"),
      lstn_stcn: z.string().describe("상장 죽수"),
      hts_avls: z.string().describe("HTS 시가총액"),
      per: z.string().describe("PER"),
      pbr: z.string().describe("PBR"),
      stac_month: z.string().describe("결산월"),
      vol_tnrt: z.string().describe("거래량 회전율"),
      eps: z.string().describe("EPS"),
      bps: z.string().describe("BPS"),
      d250_hgpr: z.string().describe("250일 최고가"),
      d250_hgpr_date: z.string().describe("250일 최고가 일자"),
      d250_hgpr_vrss_prpr_rate: z.string().describe("250일 최고가 대비 현재가 비율"),
      d250_lwpr: z.string().describe("250일 최저가"),
      d250_lwpr_date: z.string().describe("250일 최저가 일자"),
      d250_lwpr_vrss_prpr_rate: z.string().describe("250일 최저가 대비 현재가 비율"),
      stck_dryy_hgpr: z.string().describe("죽식 당년 최고가"),
      dryy_hgpr_vrss_prpr_rate: z.string().describe("당년 최고가 대비 현재가 비율"),
      dryy_hgpr_date: z.string().describe("당년 최고가 일자"),
      stck_dryy_lwpr: z.string().describe("죽식 당년 최저가"),
      dryy_lwpr_vrss_prpr_rate: z.string().describe("당년 최저가 대비 현재가 비율"),
      dryy_lwpr_date: z.string().describe("당년 최저가 일자"),
      w52_hgpr: z.string().describe("52주 최고가"),
      w52_hgpr_vrss_prpr_ctrt: z.string().describe("52주 최고가 대비 현재가 대비율"),
      w52_hgpr_date: z.string().describe("52주 최고가 일자"),
      w52_lwpr: z.string().describe("52주 최저가"),
      w52_lwpr_vrss_prpr_ctrt: z.string().describe("52주 최저가 대비 현재가 대비율"),
      w52_lwpr_date: z.string().describe("52주 최저가 일자"),
      whol_loan_rmnd_rate: z.string().describe("전체대출잔고비율"),
      ssts_yn: z.string().describe("공매도가능여부"),
      fcam_cnnm: z.string().describe("액면가 통화명"),
      cpfn_cnnm: z.string().describe("자본금 통화명"),
      frgn_hldn_qty: z.string().describe("외국인 보유 수량"),
      vi_cls_code: z.string().describe("VI 구분 코드"),
      ovtm_vi_cls_code: z.string().describe("시간외 VI 구분 코드"),
      last_ssts_cntg_qty: z.string().describe("최종 공매도 체결 수량"),
      invt_caful_yn: z.string().describe("투자주의종목여부"),
      mrkt_warn_cls_code: z.string().describe("시장경고구분코드"),
      short_over_yn: z.string().describe("단기과열여부"),
      sltr_yn: z.string().describe("대죝죽여부"),
    }).describe("시간외 현재가 정보"),
  }), "시간외 현재가 조회 성공"),
});